#ifndef FIELDS_H
#define FIELDS_H

enum {
    SWEATER_FIELD_ID = 0,
    SWEATER_FIELD_BRAND_ID,
    SWEATER_FIELD_COLOR_ID,
    SWEATER_FIELD_NECKLINE_ID,
    SWEATER_FIELD_SLEEVES_ID,
    SWEATER_FIELD_TYPE_ID,
    SWEATER_FIELD_CONDITION_ID,
    SWEATER_FIELD_SIZE_ID,
    SWEATER_FIELD_WEIGHT,
    SWEATER_FIELD_COUNT
};

enum {
    NOTE_FIELD_ID = 0,
    NOTE_FIELD_SWEATER_ID,
    NOTE_FIELD_CONTENT,
    NOTE_FIELD_COUNT
};

enum {
    PIECE_FIELD_ID = 0,
    PIECE_FIELD_SWEATER_ID,
    PIECE_FIELD_PIECE_TYPE_ID,
    PIECE_FIELD_ORIGINAL_WEIGHT,
    PIECE_FIELD_CURRENT_WEIGHT,
    PIECE_FIELD_CONTINUOUS,
    PIECE_FIELD_COUNT
};

enum {
    PIECE_TYPE_FIELD_ID = 0,
    PIECE_TYPE_FIELD_PIECE_TYPE,
    PIECE_TYPE_FIELD_COUNT
};

enum {
    BRAND_FIELD_ID = 0,
    BRAND_FIELD_BRAND,
    BRAND_FIELD_COUNT
};

enum {
    COLOR_FAMILY_FIELD_ID = 0,
    COLOR_FAMILY_FIELD_COLOR_FAMILY,
    COLOR_FAMILY_FIELD_COUNT
};

enum {
    COLOR_FIELD_ID = 0,
    COLOR_FIELD_COLOR_FAMILY_ID,
    COLOR_FIELD_COLOR,
    COLOR_FIELD_COUNT
};

enum {
    NECKLINE_FIELD_ID = 0,
    NECKLINE_FIELD_NECKLINE,
    NECKLINE_FIELD_COUNT
};

enum {
    SLEEVES_FIELD_ID = 0,
    SLEEVES_FIELD_SLEEVES,
    SLEEVES_FIELD_COUNT
};

enum {
    TYPE_FIELD_ID = 0,
    TYPE_FIELD_TYPE,
    TYPE_FIELD_COUNT
};

enum {
    CONDITION_FIELD_ID = 0,
    CONDITION_FIELD_CONDITION,
    CONDITION_FIELD_COUNT
};

enum {
    SIZE_FIELD_ID = 0,
    SIZE_FIELD_SIZE,
    SIZE_FIELD_COUNT
};

enum {
    ID_FIELD_ID = 0,
    ID_FIELD_COUNT
};

enum {
    PAGINATION_FIELD_LIMIT = 0,
    PAGINATION_FIELD_OFFSET,
    PAGINATION_FIELD_COUNT
};

enum {
    SWEATER_FILTER_FIELD_MIN_WEIGHT = 0,
    SWEATER_FILTER_FIELD_MAX_WEIGHT,
    SWEATER_FILTER_FIELD_BRAND_IDS,
    SWEATER_FILTER_FIELD_COLOR_FAMILY_IDS,
    SWEATER_FILTER_FIELD_NECKLINE_IDS,
    SWEATER_FILTER_FIELD_SLEEVES_IDS,
    SWEATER_FILTER_FIELD_TYPE_IDS,
    SWEATER_FILTER_FIELD_CONDITION_IDS,
    SWEATER_FILTER_FIELD_SIZE_IDS,
    SWEATER_FILTER_FIELD_COUNT
};

enum {
    SWEATER_SEARCH_FIELD_SWEATER_FILTER = 0,
    SWEATER_SEARCH_FIELD_PAGINATION,
    SWEATER_SEARCH_FIELD_COUNT
};

enum {
    PIECE_SEARCH_FIELD_MIN_ORIGINAL_WEIGHT = 0,
    PIECE_SEARCH_FIELD_MAX_ORIGINAL_WEIGHT,
    PIECE_SEARCH_FIELD_MIN_CURRENT_WEIGHT,
    PIECE_SEARCH_FIELD_MAX_CURRENT_WEIGHT,
    PIECE_SEARCH_FIELD_SWEATER_IDS,
    PIECE_SEARCH_FIELD_PIECE_TYPE_IDS,
    PIECE_SEARCH_FIELD_SWEATER_FILTER,
    PIECE_SEARCH_FIELD_PAGINATION,
    PIECE_SEARCH_FIELD_COUNT
};

enum {
    NOTE_SEARCH_FIELD_CONTENT = 0,
    NOTE_SEARCH_FIELD_SWEATER_IDS,
    NOTE_SEARCH_FIELD_SWEATER_FILTER,
    NOTE_SEARCH_FIELD_PAGINATION,
    NOTE_SEARCH_FIELD_COUNT
};

#endif // FIELDS_H
