#ifndef FIELD_COUNT_H
#define FIELD_COUNT_H

#define SWEATER_FIELD_COUNT 9
#define NOTE_FIELD_COUNT 3
#define PIECE_FIELD_COUNT 6
#define PIECE_TYPE_FIELD_COUNT 2
#define BRAND_FIELD_COUNT 2
#define COLOR_FAMILY_FIELD_COUNT 2
#define COLOR_FIELD_COUNT 3
#define NECKLINE_FIELD_COUNT 2
#define SLEEVES_FIELD_COUNT 2
#define TYPE_FIELD_COUNT 2
#define CONDITION_FIELD_COUNT 2
#define SIZE_FIELD_COUNT 2
#define ID_FIELD_COUNT 1
#define PAGINATION_FIELD_COUNT 2
#define SWEATER_FILTER_FIELD_COUNT 16
#define SWEATER_SEARCH_FIELD_COUNT 2
#define PIECE_SEARCH_FIELD_COUNT 10 
#define NOTE_SEARCH_FIELD_COUNT 5

#endif // FIELD_COUNT_H
